// std
#include <array>
#include <bitset>
#include <chrono>
#include <random>
#include <string>
#include <vector>
#include <limits>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <algorithm>
#include <functional>
#include <string_view>

// ext
#define GLM_FORCE_CXX20
#define GLM_FORCE_INLINE
#define GLM_FORCE_INTRINSICS
#include <glm/glm.hpp>
#include <glm/gtc/type_aligned.hpp>
#include <gtl/phmap.hpp>
#include <libmorton/morton.h>
#include <opencv2/opencv.hpp>
#include <fmt/base.h>
#include <fmt/format.h>
