// std
#include <array>
#include <bitset>
#include <chrono>
#include <random>
#include <string>
#include <vector>
#include <limits>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <algorithm>
#include <filesystem>
#include <functional>
#include <string_view>

// ext
#define GLM_FORCE_CXX20
#define GLM_FORCE_INLINE
#define GLM_FORCE_INTRINSICS
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtc/type_aligned.hpp>
#include <gtl/phmap.hpp>
#include <libmorton/morton.h>
#include <fmt/base.h>
#include <fmt/format.h>

// all the gtsam headers, mostly taken from their example
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/ISAM2.h>
#include <gtsam/nonlinear/Values.h>
#include <gtsam/geometry/Pose3.h>
#include <gtsam/geometry/Rot3.h>
#include <gtsam/slam/BetweenFactor.h>
#include <gtsam/slam/PriorFactor.h>
#include <gtsam/inference/Symbol.h>