name: Build on Ubuntu
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        compiler: [ clang++, g++ ]
        build_type: [ Debug, Release ]
    
    steps:

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y ninja-build cmake libtbb-dev libeigen3-dev libglm-dev libfmt-dev
    - name: Build and install LVR2 dependency
      run: |
        sudo apt update && sudo apt install -y libflann-dev libopenmpi-dev libtiff-dev libboost-all-dev freeglut3-dev libyaml-cpp-dev libopencv-dev libgdal-dev libgsl-dev libomp-dev
        git clone https://github.com/uos/lvr2.git && cd lvr2
        cmake -B build -G Ninja                     \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --parallel
        sudo cmake --install build

    - name: Clone
      uses: actions/checkout@v4

    - name: Build
      run: |
        cmake -B build -G Ninja                     \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --parallel