name: Build on Ubuntu
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        compiler: [clang++-13, clang++-14, clang++-15, g++-10, g++-11, g++-12]
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.11.0

    - name: Build
      run: |
        cmake -B build/${{matrix.build_type}} -GNinja
        cmake --build build/${{matrix.build_type}} --parallel