name: Build on Ubuntu
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        compiler: [ clang++, g++ ]
        build_type: [ Debug, Release ]
    
    steps:
    - name: Install core dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ninja-build cmake libtbb-dev libeigen3-dev libglm-dev libfmt-dev
        version: 1.0

    - name: Install lvr2 dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libflann-dev libopenmpi-dev libtiff-dev libboost-all-dev freeglut3-dev libyaml-cpp-dev libopencv-dev libcgal-dev libgdal-dev libgsl-dev libomp-dev
        version: 1.0

    - name: Build and install LVR2
      run: |
        git clone https://github.com/uos/lvr2.git && cd lvr2
        cmake -B build -G Ninja                     \
          -DWITH_CUDA=OFF                           \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --parallel
        sudo cmake --install build

    - name: Clone
      uses: actions/checkout@v4

    - name: Build
      run: |
        cmake -B build -G Ninja                     \
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        cmake --build build --parallel